#ifndef MEMORY_GENERAL_H                
#define MEMORY_GENERAL_H

#include "system.h"
//Sytem memory must be in [1G-16G] range.

#define PAGE_SIZE 0x1000ULL
//System with 4G
#define PHY_MEM_SIZE 0x100000000ULL
#define G_PHY_MEM_SIZE (PHY_MEM_SIZE / 0x40000000ULL)
#define MASTER_PML4 0x400000ULL
#define MASTER_PTR 0x401000ULL
#define MASTER_DIR  0x402000ULL 
#define MASTER_PAGES (0x403000ULL + (0x1000ULL * G_PHY_MEM_SIZE))
#define STATIC_BUDDY_STRUCT_START_ADDR (MASTER_PAGES + (0x200000ULL * G_PHY_MEM_SIZE))
#define MEM_START_ADDR (STATIC_BUDDY_STRUCT_START_ADDR + (0x300000ULL * G_PHY_MEM_SIZE))
#define MEM_END_ADDR PHY_MEM_SIZE
#define ALLOCATED_MEM (MEM_END_ADDR - MEM_START_ADDR)
#define POOL_START_ADDR MEM_START_ADDR
#define POOL_END_ADDR (POOL_START_ADDR + ((ALLOCATED_MEM/10ULL)-1))
#define POOL_NUM 16 
#define MEM_TO_POOL ((POOL_END_ADDR - POOL_START_ADDR)/POOL_NUM)
#define BUDDY_START_ADDR (MEM_START_ADDR+(ALLOCATED_MEM/10))
#define BUDDY_END_ADDR MEM_END_ADDR
#define BUDDY_MEM_SIZE (BUDDY_END_ADDR - BUDDY_START_ADDR)

#endif
