#ifndef MEMORY_GENERAL_H                
#define MEMORY_GENERAL_H

#include "system.h"
//Sytem memory must be in [1G-16G] range.
#define PAGE_SIZE 0x1000
#define PHY_MEM_SIZE 0x40000000
#define MEM_START_ADDR 0x1100000
#define MEM_END_ADDR PHY_MEM_SIZE
#define ALLOCATED_MEM (MEM_END_ADDR - MEM_START_ADDR)
#define POOL_START_ADDR MEM_START_ADDR
#define POOL_END_ADDR (POOL_START_ADDR + ((ALLOCATED_MEM/10)-1))
#define POOL_NUM 16 
#define MEM_TO_POOL ((POOL_END_ADDR - POOL_START_ADDR)/POOL_NUM)
#define _BUDDY_START_ADDR (MEM_START_ADDR+(ALLOCATED_MEM/10))
#define BUDDY_START_ADDR ((( _BUDDY_START_ADDR % 0x1000) !=0) ? ((( _BUDDY_START_ADDR+0x1000) - (( _BUDDY_START_ADDR+0x1000) % 0x1000))) : ( _BUDDY_START_ADDR % 0x1000))
#define BUDDY_END_ADDR MEM_END_ADDR
#define BUDDY_MEM_SIZE (BUDDY_END_ADDR - BUDDY_START_ADDR)

#endif
